(function(g){var window=this;'use strict';var O8a=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},P8a=function(a){return g.AH(a)?g.hG(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},Q8a=function(a,b){var c=new g.UH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);return c},R8a=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.x(f,g.Yw(),2);if(3!=f.j){d=f.u;if(!d)throw g.xw("gct");return g.x(f,g.FI(d),3)}e=f.u;return f.return(e.get("captions",c))})},S8a=function(a,b,c){R8a(a,b).then(function(d){d&&c(d.trackData,new g.UH(d.metadata))})},V8a=function(a){if(!T8a.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(U8a,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},W8a=function(){return g.NA("yt-player-caption-display-settings")},z4=function(){this.segments=[]},X8a=function(a,b){var c=g.Eb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.rb(a.segments,c),g.rb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Cb(a.segments,c,0,b),g.Cb(a.segments,c+1,0,b)))},Y8a=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.ea=c;this.T=d;this.D=e;this.Z=f;this.Y=this.player.V();this.C=new z4;this.I=-1;this.B=this.u=this.j=null;this.J=new g.fo(this.AR,1E3,this);this.events=new g.gF(this);g.F(this,this.J);g.F(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.Zw);this.Zw();this.AR()},Z8a=function(a){return a.j&&a.j.C?a.j.C+a.player.Fd()<a.player.getCurrentTime():!1},$8a=function(a,b){var c=g.qE(b,a.policy,{}).Ge(),d={format:"RAW",
withCredentials:!0};a.policy.Wa&&(d.method="POST",d.postBody=b.Zs()||(0,g.VW)([120,0]));a.D&&(d.responseType="arraybuffer");a.B=g.cv(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Pza(e);if(h){e=g.qE(a.u,a.policy,{});a.u.Cj(e,h);$8a(a,a.u);break a}f?a.player.va("capfail",{status:e.status}):(a.player.xj().Gi("fcb_r"),h=a.u.Za[0].Na,null!=a.T&&a.I!==h&&(f=a.u.Za[0],a.D?a.T(e.response,1E3*(f.startTime+a.player.Fd())):a.T(e.responseText,
1E3*(f.startTime+a.player.Fd())),a.I=h))}a.u=null;a.B=null}}).mj(function(e){a.u=null;
a.B=null;var f;a.player.va("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;X8a(a.C,a.u.Za[0].Na)},A4=function(a,b){g.XP.call(this,b.V());
this.u=a;this.G=b;this.B=null;this.D=!1;this.I=g.CH(this.G.V())&&!this.u.isManifestless},b9a=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.$P(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.G.V().N("html5_expose_xtags_through_caption_track")&&(n=e.xtags);else{e=f;var p=g.Q6a.get(e);null==p&&(p=a9a[e]||a9a[e.replace(/-/g,"_")],g.Q6a.set(e,p));h=p||h}c.push(new g.UH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n}))}}return c},c9a=function(a,
b){return null!=b&&b in a.u.j?a.u.j[b]:null},d9a=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.$P(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},B4=function(a,b,c,d,e,f,h){var l={};
Object.assign(l,b);Object.assign(l,a.params);Object.assign(l,c);var m={};Object.assign(m,b.le);a.params.le&&Object.assign(m,a.params.le);Object.assign(m,c.le);l.le=m;g.V.call(this,{F:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:1===l.Ch?"rtl":"ltr",tabindex:"0",lang:l.lang},W:[{F:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.Aa=!1;this.u=a;this.Ka=this.Ba=null;this.playerWidth=f;this.playerHeight=h;this.I=null;this.maxWidth=.96*f;this.Wa=.96*
h;this.j=l;this.xc=c;this.ea=b;this.C=this.Da("captions-text");this.Tb=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");a=e/360*16;e>=d&&(d=640,h/=f,1.3<h&&(d/=h),a=f/d*16);this.Ma=a;this.type=0;this.Xa=this.Ma*e9a(m);f=new g.aA(this.element,!0);g.F(this,f);f.subscribe("dragstart",this.PV,this);f.subscribe("dragmove",this.OV,this);f.subscribe("dragend",this.NV,this);this.kb=this.ib=this.yb=this.qb=0;m="";this.j.windowOpacity&&
(f=V8a(this.j.windowColor),m="rgba("+f[0]+","+f[1]+","+f[2]+","+this.j.windowOpacity+")");f={"background-color":m,display:!1===this.j.isVisible?"none":"","text-align":f9a[this.j.textAlign]};this.Tb&&(f["border-radius"]=m?this.Xa/8+"px":"");if(this.B=2===this.u.params.Ch||3===this.u.params.Ch)m=this.element,h="vertical-rl",1===this.j.qM&&(h="vertical-lr"),g.Re&&(h="vertical-lr"===h?"tb-lr":"tb-rl"),g.Gl(m,"-o-writing-mode",h),g.Gl(m,"-webkit-writing-mode",h),g.Gl(m,"writing-mode",h),g.Gl(m,"text-orientation",
"upright"),g.no(m,"ytp-vertical-caption"),3===this.u.params.Ch&&(g.Gl(m,"text-orientation",""),g.Gl(m,"transform","rotate(180deg)"));g.Gl(this.element,f);switch(this.j.wk){case 0:case 1:case 2:g.no(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.no(this.element,"ytp-caption-window-bottom")}},e9a=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},g9a=function(a,b){var c={},d=b.background?b.background:a.j.le.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.le.backgroundOpacity;d=V8a(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Tb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Xa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ma*e9a(b)+"px";d=1;e=b.color||a.j.le.color;if(b.color||null!=b.textOpacity)e=V8a(e),d=null==b.textOpacity?a.j.le.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.NH&&(h=e=b.NH);var l=a.Ma/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.nv()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.le.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.r_&&(c.visibility="hidden");1===b.XQ&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.EH||g.vw,3===a.u.params.Ch?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.hm||2===b.hm||3===b.hm||4===b.hm||5===b.hm)if(g.EH)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.hm){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},h9a=function(a){a.I=g.Ve("SPAN");
g.Gl(a.I,{display:"block"});g.no(a.I,"caption-visual-line");a.C.appendChild(a.I)},i9a=function(a,b){var c=g.Ve("SPAN");
g.Gl(c,{display:"inline-block","white-space":"pre-wrap"});g.Gl(c,g9a(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.Gl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Gl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},j9a=function(a,b,c){a.Aa=a.Aa||!!c;
var d={};Object.assign(d,a.j.le);Object.assign(d,c||b.j);Object.assign(d,a.xc.le);(c=!a.I)&&h9a(a);for(var e=a.Ba&&a.Ka&&g.gd(d,a.Ka)?a.Ba:i9a(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(h9a(a),e=i9a(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.We(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.EH||!g.Il(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Il(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Mc?g.Gl(e,m,"1em"):g.Gl(e,m,"0.5em")))}a.Ka=d;a.Ba=e;a.D.push(b)},C4=function(a,b,c,d){g.XP.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.C=b.LH},D4=function(a,b,c,d,e,f,h,l){B4.call(this,a,b,c,d,e,f,h,l);
this.type=1},E4=function(a,b,c,d,e,f,h,l){B4.call(this,a,b,c,d,e,f,h,l);
this.type=2;this.J=[];this.Z=this.T=this.Oa=0;this.oa=NaN;this.Nb=0;this.Wb=null;this.Sa=new g.fo(this.C2,433,this);g.no(this.element,"ytp-caption-window-rollup");g.F(this,this.Sa);g.Gl(this.element,"overflow","hidden")},k9a=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.qM&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},l9a=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Ap,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.T=d;b=Math;c=b.max;isNaN(a.oa)&&((d=a.j.eq)?(e=g.Ve("SPAN"),g.df(e,"\u2013".repeat(d)),g.Gl(e,g9a(a,a.j.le)),a.C.appendChild(e),a.oa=e.offsetWidth,a.C.removeChild(e)):a.oa=0);d=a.C;a.Z=c.call(b,a.oa,a.Nb,(a.B?d.offsetHeight:d.offsetWidth)+1)},m9a=function(a,b){l9a(a);
var c=a.J.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.T-c;if(c!==a.Oa){var d=0<c&&0===a.Oa;b||isNaN(c)||d||(g.no(a.element,"ytp-rollup-mode"),g.go(a.Sa));g.Gl(a.C,"transform",k9a(a,c));a.Oa=c}l9a(a)},F4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.pB.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},G4=function(a,b,c,d,e){g.pB.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},n9a=function(a){var b="_"+H4++;
return new G4(0,0x8000000000000,0,b,a)},p9a=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.uf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=o9a(l.textContent,n.textContent,p.textContent,f.textContent,h);return new F4(a,b,e,c,l,d,m)}switch(m.uf){case 9:case 10:m.hm=1;break;case 11:m.hm=2;break;case 12:m.hm=3;break;case 13:m.hm=4;break;case 14:m.hm=5}return new F4(a,b,e,c,l.textContent||"",d,m)},o9a=function(a,b,c,d,e){var f=g.nv(),h=
f?g.Ve("DIV"):g.Ve("RUBY"),l=g.Ve("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ve("DIV"):g.Ve("RP");a.textContent=b;h.appendChild(a);b=f?g.Ve("DIV"):g.Ve("RT");b.textContent=c;h.appendChild(b);c=e.uf;if(10===c||11===c||12===c||13===c||14===c)if(g.Gl(b,"text-emphasis-style","filled circle"),g.Gl(b,"text-emphasis-color","currentcolor"),g.Gl(b,"webkit-text-emphasis","filled circle"),11===e.uf||13===e.uf)g.Gl(b,"webkit-text-emphasis-position","under left"),g.Gl(b,"text-emphasis-position","under left");c=!0;if(4===e.uf||7===e.uf||12===e.uf||
14===e.uf)g.Gl(h,"ruby-position","over"),g.Gl(h,"-webkit-ruby-position","before");else if(5===e.uf||6===e.uf||11===e.uf||13===e.uf)g.Gl(h,"ruby-position","under"),g.Gl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ve("DIV"):g.Ve("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Gl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Gl(f,"display","none"),f=f.nextElementSibling,g.Gl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Gl(h.lastElementChild,"display","none"),d?(g.Gl(h,"padding-top","0.6em"),g.Gl(f,"top","0")):(g.Gl(h,"padding-bottom","0.6em"),g.Gl(f,"bottom","0")));return h},I4=function(){g.C.apply(this,arguments)},J4=function(a){I4.call(this);
this.C=a;this.pens={};this.T={};this.Z={};this.D="_"+H4++;this.J={};this.B=this.j=null;this.I=!0},K4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},L4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},M4=function(a,b){a=K4(a,b);
return void 0!==a?a:null},O4=function(a,b){a=a.getAttribute(b);
if(null!=a)return N4.test(a),a},q9a=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=M4(b,"mh");null!=a&&(c.Uw=a);a=M4(b,"ju");null!=a&&(c.textAlign=a);a=M4(b,"pd");null!=a&&(c.Ch=a);a=M4(b,"sd");null!=a&&(c.qM=a);a=O4(b,"wfc");null!=a&&(c.windowColor=a);b=K4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},r9a=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.T[d]);a=M4(b,"ap");null!=a&&(c.wk=a);a=K4(b,"cc");null!=a&&(c.eq=a);a=K4(b,"ah");null!=a&&(c.bj=a);a=K4(b,"rc");null!=a&&(c.Ap=a);b=K4(b,"av");null!=b&&(c.jm=b);return c},s9a=function(a,b,c,d){var e={};
Object.assign(e,r9a(a,b));Object.assign(e,q9a(a,b));d?g.gd(e,a.C)?(d=a.D,e=a.C):d="_"+H4++:d=b.getAttribute("id")||"_"+H4++;a=K4(b,"t")+c;b=K4(b,"d")||0x8000000000000;if(2===e.Ch||3===e.Ch)c=e.Ap,e.Ap=e.eq,e.eq=c;return new G4(a,b,0,d,e)},P4=function(a){I4.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},Q4=function(a){a=g.ne(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},t9a=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Ap=a);b=b.ccColCount;void 0!==b&&(f.eq=b);if(2===f.Ch||3===f.Ch)b=f.Ap,f.Ap=f.eq,f.eq=b;return new G4(c,d,0,e,f)},v9a=function(){this.B=this.time=this.mode=this.u=0;
this.C=new u9a(this);this.D=new u9a(this);this.j=[];this.clear()},x9a=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Fs:a,
Zp:b,result:0};a=w9a[a];b=w9a[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Zp===d;if(d)return{Fs:a,Zp:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Fs:a,Zp:b,result:2};return{Fs:a,Zp:b,result:3}},z9a=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,y9a(a.C,b,c,d))},A9a=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?z9a(a,d.rP,d.sP,b):1===d.type&&a.u&496&&y9a(a.D,d.rP,d.sP,b);a.j.length=0},R4=function(){this.type=0},S4=function(){this.state=this.Zp=this.Fs=0},B9a=function(){this.timestamp=this.j=0},T4=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new R4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new B9a}},U4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},G9a=function(a,b){switch(a){case 0:return C9a[(b&127)-32];
case 1:return D9a[b&15];case 2:return E9a[b&31];case 3:return F9a[b&31]}return 0},V4=function(a){return a.B[a.row][a.u]},W4=function(a,b,c){2<=b&&1<a.u&&(--a.u,V4(a).j=0);
var d=V4(a);d.timestamp=a.D.time+0;d.j=G9a(b,c);32>a.u&&a.u++},H9a=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},X4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},I9a=function(a){a.row=0<a.j?a.j:1;
a.u=1;X4(a,0,15)},J9a=function(a){this.B=a;
this.D=0;this.style=new R4;this.I=new T4(this.B);this.J=new T4(this.B);this.text=new T4(this.B);this.u=this.I;this.C=this.J;this.j=this.u},K9a=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(U4(d,c),I9a(a.u),I9a(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(U4(d,c),X4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},L9a=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},M9a=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},u9a=function(a){this.j=a;
this.D=0;this.B=new J9a(this.j);this.I=new J9a(this.j);this.u=new S4;this.C=this.B},y9a=function(a,b,c,d){a.u.update();
b=x9a(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Fs;c=b.Zp;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&W4(a,0,b),c&96&&W4(a,0,c),0!==b&&0!==c&&3===a.style.type&&U4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Fs=e,b.Zp=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;H9a(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));X4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:W4(b.j,0,32);break a;case 48:57===c?(d=b.j,V4(d).j=0,32>d.u&&d.u++):W4(b.j,1,c&15)}break;case 2:c&32&&W4(b.j,2,c&31);break;case 3:c&32&&W4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:L9a(b);
break;case 33:d=b.j;1<d.u&&(--d.u,V4(d).j=0);break;case 36:d=b.j;b=V4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:K9a(b,2,d);break;case 38:K9a(b,3,d);break;case 39:K9a(b,4,d);break;case 40:W4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);I9a(d);M9a(b);break;case 43:M9a(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:U4(a,d)}X4(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;U4(a,d);H9a(a,b,b+1,a.j-1);X4(a,a.row,1)}break;case 46:X4(b.C,0,15);break;case 47:U4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,L9a(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},N9a=function(){},Y4=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},Z4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},$4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},a5=function(a,b){I4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new v9a;this.j.u=1<<this.track},P9a=function(a){if("string"===typeof a)return!1;
a=new Y4(a,8,0);return O9a(a)},O9a=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==$4(a))return!1;
a.version=Z4(a);if(1<a.version)return!1;Z4(a);Z4(a);Z4(a);return!0},b5=function(){I4.call(this)},Q9a=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new F4(b,c,d,e.id,p.nodeValue,f||0<n,g.dd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Q9a(a,b,c,d,e,!0,p,q,m)}}},R9a=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},S9a=function(a,b,c,d){d=Object.assign({Uw:0},d);
return new G4(a,b,c,"_"+H4++,d)},c5=function(a,b){g.C.call(this);
this.G=a;this.Y=b;this.parser=null;this.j=this.G.Aw()},Y9a=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=T9a(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.gM;l="string"!==typeof q?l.concat(U9a(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(V9a(a,q,r)):l.concat(W9a(a,c,q,r))}var w=l}catch(y){g.kA(y),a.clear(),w=[]}if(0!==w.length)return w}b=X9a(b);if(!b)return[];try{return"string"!==typeof b?U9a(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?V9a(a,b,d):W9a(a,c,b,d)}catch(y){return g.kA(y),a.clear(),[]}},X9a=function(a){if("string"===
typeof a||P9a(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.sD(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.dD(a)},T9a=function(a,b,c){if("string"===typeof b||P9a(b))return[{trackData:b,
gM:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Dya(d);if(a.j&&e){var f=g.vya(e),h=g.wya(e);e=e.j;f&&e&&a.j.wB(e,f,h)}f=g.BD(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.dD(e),a.push({trackData:e,gM:c+1E3*h});Z9a(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
Z9a=function(a,b,c){var d=g.sD(a,0,1836476516),e=9E4;
d&&(e=g.tD(d)||9E4);d=0;var f=g.BD(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.sD(a,l.dataOffset,1953653094))&&(l=g.sD(a,l.dataOffset,1952867444))&&(l=g.zD(l)/e*1E3,0===h&&(d=l),b[h].gM=l-d+c||c*h*1E3)}},U9a=function(a,b,c,d,e){if(!P9a(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new a5(e,b));return a.parser.u(c,d)},V9a=function(a,b,c){a.parser||(a.parser=new b5);
a=a.parser.u(b,c);.01>Math.random()&&g.lA(Error("Deprecated subtitles format in web player: WebVTT"));return a},W9a=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new P4($9a(b))),a.parser.u(c,d)}catch(f){return g.kA(f),[]}var e=g.j2a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new J4($9a(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},$9a=function(a){var b=
{};
if(a=g.XH(a))b.lang=a,g.x3a.test(a)&&(b.Ch=1);return b},d5=function(a){g.UP.call(this,a);
var b=this;this.G=a;this.Y=this.G.V();this.videoData=this.G.getVideoData();this.qb=this.G.fb();this.B={le:{}};this.D={le:{}};this.Ba=[];this.Z={};this.Sa={};this.ya=!1;this.Wb=g.IJ(this.videoData);this.ib=g.EJa(this.videoData,this.G);this.Tb=!!this.videoData.captionTracks.length;this.wc=!!this.videoData.Qd;this.Wa="3"===this.Y.controlsType;this.u=this.I=this.J=this.Oa=this.kb=null;this.Xa=new c5(this.G,this.Y);this.j=null;this.Aa=new g.gF(this);this.ea=new g.V({F:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.T={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.Yo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Mo(d));this.storage=c;var e;this.yb=!(null==(e=a.Zd())||!e.qB());this.C=a$a(this);this.oa=!this.C&&this.Wa&&this.yb&&this.ib;g.F(this,this.Xa);this.C?this.Ma=this.Ka=null:(this.Ka=new g.co(this.HM,void 0,this),g.F(this,this.Ka),this.Ma=new g.fo(this.Z3,2E3,this),g.F(this,this.Ma));g.F(this,this.Aa);this.Y.N("caption_window_container_killswitch")||
g.kP(this.player,this.ea.element,4);g.F(this,this.ea);this.C||this.Aa.S(a,"resize",this.KM);(this.Nb=g.gH(this.Y)&&!g.Qz()&&!this.G.isFullscreen()&&!this.C&&!this.oa)&&this.Aa.S(a,"resize",this.E1);this.Aa.S(a,"onPlaybackAudioChange",this.O0);this.Aa.S(a,g.rB("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.S(a,g.sB("captions"),function(f){b.onCueRangeExit(f)});
b$a(this,W8a()||{})},e$a=function(a){if(1===a.Y.ib||1===a.videoData.XJ||"alwayson"===g.rJ(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.Y.ib){if(g.AH(a.Y))var c=c$a(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=O8a(a.player.getAudioTrack(),g.AH(a.Y));var d=g.rJ(a.videoData,"yt:cc");if(void 0===d$a(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.rJ(a.videoData,"yt:cc")},e5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.u||"FORCED_ON"===a.B},d$a=function(a){var b=void 0,c=g.Rv(g.Qv.getInstance(),65);
if(g.AH(a.Y)&&null!=c){if(null!=c$a(a))return!1;b=!c}return b},f$a=function(a){var b;
a.Wb?b=new C4(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.ib?b=new A4(a.videoData.j,a.player):a.Tb?b=new g.YP(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.aQ(a.Y,a.videoData.Qd,a.videoData.videoId,g.cEa(a.videoData),a.videoData.Cm);return b},D5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.wc?!1:a.Tb?!1:!0);b=b||!!g.Rv(g.Qv.getInstance(),66);b=g.VP(a.u.j,b);if(P8a(a.Y)){var c=a.G.isInline()?void 0:g.NA("yt-player-caption-sticky-language");c=[c,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.rJ(a.videoData,"yt:cc_default_lang")];for(var d=!1,e=0;e<c.length;e++){var f=c[e];if(f){d=!0;for(var h=0;h<b.length;h++)if(g.XH(b[h])===f)return b[h];f=f.split("-")[0];for(h=0;h<b.length;h++)if(g.XH(b[h])===f)return b[h]}}if(d){var l;return(null==(l=a.I)?void 0:l.j)||
f5(a)}}else for(l=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.rJ(a.videoData,"yt:cc_default_lang")],c=0;c<l.length;c++)for(d=0;d<b.length;d++)if(g.XH(b[d])===l[c])return b[d];return a.I&&a.I.j?a.I.j:(l=b.find(function(m){return m.isDefault}))?l:b[0]||f5(a)}return null},f5=function(a){return a.I&&a.I.u},P5=function(a){var b=f5(a);
return!!b&&a.j===b},g$a=function(a){g.VP(a.u.j,!0);
var b=O8a(a.player.getAudioTrack(),g.AH(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=D5(a,a.ya):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&e5(a)?c=f5(a):d$a(a)||a.ya||e$a(a)?c=D5(a,a.ya):e5(a)&&(c=f5(a));if(a.C||a.oa){var d=g.VP(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Ve("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.VH(f));h.setAttribute("srclang",g.XH(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.u.Ys(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.G.Zd();c.Ly(b);c=c.Ff();a.yb&&a.Aa.S(c.textTracks,"change",a.n3)}else!a.j&&c&&X5(a,c),a.player.Qa("onCaptionsTrackListChanged"),a.player.Qa("onApiChange")},h$a=function(a,b){var c=a.G.Zd().Ff().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},X5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ya=c,a.ya&&(g.AH(a.Y)?Z5(a,!!b):$5(a,!!b)));a.j=b;e5(a)&&(a.j=f5(a));a.load()},j$a=function(a,b){if(b instanceof G4){var c=a.Z[b.id];
c&&c.u!==b&&(c.dispose(),delete a.Z[b.id],c=null);c||(c=i$a(a,b))&&(a.Z[b.id]=c)}else c=b.windowId,a.Sa[c]||(a.Sa[c]=[]),a.Sa[c].push(b)},k$a=function(a,b){a.Y.N("caption_window_container_killswitch")?g.kP(a.player,b,4):a.ea.element.appendChild(b)},i$a=function(a,b){var c=a.qb.getVideoContentRect(!0).height,d=a.qb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.XH(a.j):null;e&&g.x3a.test(e)&&(b.params.Ch=1);var f=a.qb.getPlayerSize();c*=a.T.height;d*=a.T.width;e=f.height*a.T.height;f=f.width*a.T.width;"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Uw?b.params.Uw:1<b.j.length?1:0){case 1:return new D4(b,a.B,a.D,d,c,f,e,a.Y.experiments);case 2:return new E4(b,a.B,a.D,d,c,f,e,a.Y.experiments);default:return new B4(b,a.B,a.D,d,c,f,e,a.Y.experiments)}},b$a=function(a,b,c){c=
void 0===c?!1:c;
var d=a6.le;a.B={};Object.assign(a.B,a6);a.B.le={};Object.assign(a.B.le,d);a.D={le:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;N4.test(f);e.le.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;N4.test(f);e.le.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||a6.windowColor;N4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.le.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.le.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.le;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.le.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=a6.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.le.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.le.fontFamily=f;a.loaded&&a.KM();c&&g.MA("yt-player-caption-display-settings",b,2592E3)},m$a=function(a,b,c){b&&!a.J?(b=n9a({Ch:0,
lang:"en"}),a.J=[b,new F4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.ye(a.J)):!b&&a.J&&(l$a(a,a.J),a.J=null)},l$a=function(a,b){a.player.Ah(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.sb(a.Ba,c.value);g.eo(a.Ka)},n$a=function(a,b){b&&(a.T={top:b.top,
right:b.right,bottom:b.bottom,left:b.left,width:1-b.left-b.right,height:1-b.top-b.bottom},a.ea.element.style.top=100*a.T.top+"%",a.ea.element.style.left=100*a.T.left+"%",a.ea.element.style.width=100*a.T.width+"%",a.ea.element.style.height=100*a.T.height+"%")},$5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Z5=function(a,b){a.G.isInline()||g.MA("yt-player-sticky-caption",b,2592E3)},c$a=function(a){if(!a.G.isInline())return g.NA("yt-player-sticky-caption")},a$a=function(a){var b,
c=!(null==(b=a.G.Zd())||!b.pB());
return a.Wa&&c&&!a.ib};
g.AU.prototype.wz=g.ba(39,function(a){var b=2;this.Ma.has(a)?b=0:g.kNa(this,a)&&(b=1);return b});
g.DX.prototype.wz=g.ba(38,function(a){return this.od.wz(a)});
g.AU.prototype.wB=g.ba(37,function(a,b,c){this.Ba.set(a,{Rs:b,Iy:c})});
g.DX.prototype.wB=g.ba(36,function(a,b,c){this.od.wB(a,b,c)});
g.oQ.prototype.Tv=g.ba(31,function(){for(var a=g.Le(document,"track",void 0,this.j),b=0;b<a.length;b++)g.af(a[b])});
g.kU.prototype.Tv=g.ba(30,function(){this.mediaElement.Tv()});
g.oQ.prototype.qB=g.ba(29,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.kU.prototype.qB=g.ba(28,function(){return this.mediaElement.qB()});
g.oQ.prototype.pB=g.ba(27,function(){return!!this.j.textTracks});
g.kU.prototype.pB=g.ba(26,function(){return this.mediaElement.pB()});
g.oQ.prototype.Ly=g.ba(25,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.kU.prototype.Ly=g.ba(24,function(a){this.mediaElement.Ly(a)});
g.XP.prototype.iL=g.ba(23,function(){return!1});
g.XP.prototype.Yq=g.ba(22,function(){});
g.YP.prototype.Yq=g.ba(21,function(a,b,c){var d=this;this.isDisposed();b=this.Ys(a,b);this.Lp();this.u=g.$u(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.aQ.prototype.Yq=g.ba(20,function(a,b,c){var d=this;this.isDisposed();b=this.Ys(a,b);this.Lp();this.u=g.$u(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.qX.prototype.Mz=g.ba(10,function(){return this.I});
g.mZ.prototype.Mz=g.ba(9,function(){var a;return(null==(a=g.BO(this))?void 0:a.Aw())||null});
g.dP.prototype.Aw=g.ba(8,function(){return this.app.Mz()});
g.ZY.prototype.Aw=g.ba(7,function(){var a;return(null==(a=this.Ja)?void 0:a.Mz())||null});
g.SC.prototype.vD=g.ba(3,function(a){return(a=this.dn(a))?a.j:0});
g.OE.prototype.vD=g.ba(2,function(){return 0});
var U8a=/#(.)(.)(.)/,T8a=/^#(?:[0-9a-f]{3}){1,2}$/i,a9a={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgn:"Western Balochi",bho:"Bhojpuri",
bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",
chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",
goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",
ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",
kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",
lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",
mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",
ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};z4.prototype.contains=function(a){a=g.Eb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
z4.prototype.length=function(){return this.segments.length/2};
g.v(Y8a,g.C);g.k=Y8a.prototype;g.k.ra=function(){g.C.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.Zw=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Fd();var b=this.j;this.j=g.gb(this.ea.Qo(a).Za);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new z4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.AR=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Tp(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Ay(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Aw()){var c=a.Za[0].j.info.id,d=a.Za[0].Na,e=a.Za[0].B;if(this.policy.Wa){if(b=b.Zs(e,d,c,3))a.J=b}else if(c=b.hn(e,d,c,3))if(b=b.wz(d),0===b)c&&(a.u=new g.LC(c));else if(2===b){this.J.start();Z8a(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.Za[0].duration?(this.C.contains(a.Za[0].Na)||$8a(this,a),this.j=g.gb(a.Za)):!this.Y.N("force_caption_seek_for_live_killswitch")&&Z8a(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(A4,g.XP);g.k=A4.prototype;g.k.Yq=function(a,b,c){var d=this;this.Lp();b=c9a(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?d9a(this,b,"386"):d9a(this,b));if(b){var e=1E3*(b.index.vD(b.index.Fl())-b.index.getStartTime(b.index.Fl())),f=new g.ZP(this.Y);this.B=new Y8a(f,this.G,b,function(h,l){c(h,a,l,e)},this.I||g.ME(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.iL=function(){var a=this.D;this.D=!1;return a};
g.k.Rw=function(a){var b=this.I?[new g.UH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.UH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?b9a(this,"386"):b9a(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.WP(this.j,c.value);a()};
g.k.Lp=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Ys=function(){return""};
var N4=/^#(?:[0-9a-f]{3}){1,2}$/i;var f9a=["left","right","center","justify"];g.v(B4,g.V);g.k=B4.prototype;g.k.PV=function(a,b){this.ib=a;this.kb=b;var c=g.Pl(this.element,this.element.parentElement);this.qb=a-c.x;this.yb=b-c.y};
g.k.OV=function(a,b){if(a!==this.ib||b!==this.kb){g.mo(this.element,"ytp-dragging")||g.no(this.element,"ytp-dragging");var c=g.Rl(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.yb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ne(e,0,2));var f=(d+c.height/2)/this.Wa*3;f=Math.floor(g.ne(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ne(a,0,1);c=(d+f/2*c.height)/this.Wa;c=100*g.ne(c,0,1);this.u.params.wk=b;this.u.params.jm=c;this.u.params.bj=a;this.u.params.isDefault=
!1;this.j.wk=b;this.j.jm=c;this.j.bj=a;this.j.isDefault=!1;this.ea.wk=b;this.ea.jm=c;this.ea.bj=a;this.ea.isDefault=!1;this.yT()}};
g.k.NV=function(){g.po(this.element,"ytp-dragging")};
g.k.yT=function(){this.yx(this.D)};
g.k.getType=function(){return this.type};
g.k.yx=function(a){var b=Math.min(this.mQ(),this.maxWidth),c=this.lQ(),d="";3===this.u.params.Ch&&(d="rotate(180deg)");g.Gl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.vH(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.bj+2;d=this.j.wk;switch(d){case 0:case 3:case 6:(b=this.j.le.fontSizeIncrement)&&0<b&&2!==this.j.Ch&&3!==
this.j.Ch&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.j.jm+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Gl(this.element,
a)};
g.k.vH=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.Aa||this.D.length>b)b=0,this.Aa=!1,this.D=[],this.I=this.Ka=this.Ba=null,g.Xe(this.C);for(;b<a.length;b++)j9a(this,a[b])};
g.k.mQ=function(){return 0};
g.k.lQ=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.v(C4,g.XP);C4.prototype.Yq=function(a,b,c){S8a(this.videoData.videoId,a.vssId,c)};
C4.prototype.Rw=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.WP(this.j,c.value);a()};g.v(D4,B4);D4.prototype.vH=function(a){var b=this.u.j;B4.prototype.vH.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,o$a);var e=c.j;var f=d}j9a(this,c,d)}};
var o$a={r_:!0};g.v(E4,B4);g.k=E4.prototype;g.k.yT=function(){g.ho(this.Sa)};
g.k.C2=function(){g.po(this.element,"ytp-rollup-mode");this.yx(this.Wb,!0)};
g.k.lQ=function(){return this.B?this.Z:this.T};
g.k.mQ=function(){return this.B?this.T:this.Z};
g.k.yx=function(a,b){this.Wb=a;if(this.u.params.Ap){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.Nb=this.Z;this.T=this.Z=0;B4.prototype.yx.call(this,a);m9a(this,b)}B4.prototype.yx.call(this,a)};g.v(F4,g.pB);F4.prototype.toString=function(){return g.pB.prototype.toString.call(this)};g.v(G4,g.pB);G4.prototype.toString=function(){return g.pB.prototype.toString.call(this)};
var H4=0;g.v(I4,g.C);I4.prototype.u=function(){return[]};
I4.prototype.reset=function(){};g.v(J4,I4);J4.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
J4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=L4(a,"b");
null!=l&&(h.bold=l);l=L4(a,"i");null!=l&&(h.italic=l);l=L4(a,"u");null!=l&&(h.underline=l);l=M4(a,"et");null!=l&&(h.charEdgeStyle=l);l=M4(a,"of");null!=l&&(h.offset=l);l=O4(a,"bc");null!=l&&(h.background=l);l=O4(a,"ec");null!=l&&(h.NH=l);l=O4(a,"fc");null!=l&&(h.color=l);l=M4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=K4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=K4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=K4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=M4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.uf=10<l?l-1:l);a=M4(a,"hg");null!=a&&(h.XQ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=q9a(this,a);break;case "wp":c=a.getAttribute("id"),this.T[c]=r9a(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=s9a(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!L4(a,"a");l=(K4(a,"t")||0)+l;var m=K4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],y=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.uf&&(1===w.uf?(w=q.slice(r,r+
4),4===w.length&&(y=p9a(l,m,f,h,n,w,this.pens),r+=3)):y=p9a(l,m,f,h,n,[z],this.pens)),!y){var B=z;y=l;z=m;w=f;var D=h,G=n,E=B.textContent?B.textContent:"",J=B.getAttribute("p");J=J?this.pens[J]:null;B=K4(B,"t")||0;y=new F4(y+B,z-B,G,w,E,D,J)}}else y=new F4(l,m,n,f,w.textContent||"",h,p);c.push(y);this.B=y}if(0<c.length)for(c[0].windowId===this.D&&(this.j=s9a(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var p$a=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(P4,I4);P4.prototype.reset=function(){this.B.clear()};
P4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.NH=Q4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=Q4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=Q4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.uf=10<h?h-1:h,f.hm=p$a.get(f.uf));e.hgHorizGroup&&(f.XQ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Uw=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ch=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.qM=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=Q4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.bj=e.ahHorPos),void 0!==e.apPoint&&(f.wk=e.apPoint),void 0!==e.avVerPos&&(f.jm=e.avVerPos),void 0!==e.ccCols&&(f.eq=e.ccCols),void 0!==e.rcRows&&(f.Ap=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=t9a(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+H4++,h=t9a(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var y=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Uw?h.params.Uw:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.uf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.uf&&2===B.uf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.uf||3>B.uf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.uf&&2===B.uf?!0:!1)):r=!1}if(r){y=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);w=o9a(w,y,B,r,D);m=new F4(d,e,n,f,w,m,z);l+=3}else m=new F4(d+y,e-y,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};v9a.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
v9a.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var w9a=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];R4.prototype.set=function(a){this.type=a};
R4.prototype.get=function(){return this.type};
S4.prototype.clear=function(){this.state=0};
S4.prototype.update=function(){this.state=2===this.state?1:0};
S4.prototype.isValid=function(){return 0!==this.state};
S4.prototype.matches=function(a,b){return this.isValid()&&a===this.Fs&&b===this.Zp};
B9a.prototype.reset=function(){this.timestamp=this.j=0};
T4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
T4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
T4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var C9a=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],D9a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],E9a=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],F9a=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];J9a.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
u9a.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};N9a.prototype.C=function(){};g.v(Y4,N9a);Y4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+H4++;c=c/1E3-this.I;d=d/1E3-this.I;a=new G4(c,d-c,5,f,{textAlign:0,wk:0,bj:2.5*b,jm:5.33*a});e=new F4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(a5,I4);a5.prototype.u=function(a){a=new Y4(a,a.byteLength,this.B);if(O9a(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=$4(a)*(1E3/45):1===a.version&&(a.B=4294967296*$4(a)+$4(a)),a.D=Z4(a);0<a.D;a.D--){var b=Z4(a),c=Z4(a),d=Z4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,rP:c,sP:d,order:b.j.length}))}A9a(this.j,a);return a.u}return[]};
a5.prototype.reset=function(){this.j.clear()};g.v(b5,I4);
b5.prototype.u=function(a,b){var c=[];a=a.split(q$a);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!r$a.test(e)){var h=s$a.exec(e);if(h&&4<=h.length){var l=R9a(h[1]),m=R9a(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var z=y[1];switch(y[0]){case "line":y=z.split(",");y[0].endsWith("%")&&(p=y[0],h.jm=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
z.split(",");r=y[0];h.bj=Number.parseInt(r,10);2===y.length&&(w=y[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.bj=0;break;case 1:h.bj=100;break;case 2:h.bj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.wk=q}e=e.substring(s$a.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=S9a(l,m,5,w),m=new F4(l,m,5,f.id,h,!1,g.dd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(t$a),1===q.length?(h=5,w=S9a(l,m,h,w)):(p=h=6,w=Object.assign({eq:32},w),w=new G4(l,m,p,"_"+H4++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(y=g.j2a("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(z=y.createElement("span"),z.appendChild(y.createTextNode(n))):z=y.firstChild,Q9a(this,p,m-(p-l),h,w,0<r,z,e,c)):p=R9a(n)+f}s$a.lastIndex=0}}return c};
var r$a=/^NOTE/,q$a=/(?:\r\n|\r|\n){2,}/,s$a=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),t$a=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.mU.LD(b5,{u:"wvppt"});g.v(c5,g.C);c5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
c5.prototype.reset=function(){this.parser&&this.parser.reset()};
c5.prototype.ra=function(){g.C.prototype.ra.call(this);this.clear()};var a6={windowColor:"#080808",windowOpacity:0,textAlign:2,wk:7,bj:50,jm:100,isDefault:!0,le:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(d5,g.UP);g.k=d5.prototype;g.k.ra=function(){if(this.C||this.oa){var a=this.G.Zd();a&&!a.isDisposed()&&a.Tv()}else m$a(this,!1);g.UP.prototype.ra.call(this)};
g.k.uu=function(){if(this.Wa)return this.C||this.oa;var a=O8a(this.player.getAudioTrack(),g.AH(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?e5(this):d$a(this)||e5(this)?!0:e$a(this)};
g.k.load=function(){var a=this;g.UP.prototype.load.call(this);this.I=this.player.getAudioTrack();this.u?this.j&&(this.Xa.clear(),this.C?h$a(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Yq(this.j,"json3",function(b,c,d,e){if(b){a.u.iL()&&(a.Ba=[],a.G.Ef("captions"),g.eo(a.Ka),a.Xa.reset());b=Y9a(a.Xa,b,c,d,e);a.player.ye(b,void 0,a.ib);if(!(!a.ya||a.oa||P5(a)||g.qH(a.Y)||g.jH(a.Y)||g.kH(a.Y)||a.player.isInline())){g.io(a.Ma);b=n9a({wk:0,bj:5,jm:5,Ap:2,textAlign:0,Ch:0,lang:"en"});a.Oa=
[b];d=["Click "," for settings"];a.kb||(e=new g.uM(g.MM()),g.F(a,e),a.kb=e.element);e=b.end-b.start;var f=g.VH(a.j);f&&a.Oa.push(new F4(b.start,e,0,b.id,f));a.Oa.push(new F4(b.start,e,0,b.id,d[0]),new F4(b.start,e,0,b.id,a.kb,!0),new F4(b.start,e,0,b.id,d[1],!0));a.player.ye(a.Oa);g.go(a.Ma)}!a.ya||a.oa||P5(a)||(g.AH(a.Y)?Z5(a,!0):$5(a,!0),a.I&&(a.I.C=a.j),a.player.Du());var h;null==(h=a.G.Mc())||h.va("cc",{kind:c.kind});a.ya=!1}}),this.C||this.oa||P5(this)||this.player.Qa("captionschanged",g.WH(this.j))):
(this.u=f$a(this),g.F(this,this.u),this.u.Rw(function(){g$a(a)}))};
g.k.unload=function(){this.C&&this.j?h$a(this,!1):(this.Ma&&g.io(this.Ma),this.player.Ef("captions"),this.Ba=[],this.u&&this.u.Lp(),this.Xa.clear(),this.J&&this.player.ye(this.J),this.KM());g.UP.prototype.unload.call(this);this.player.Du();this.player.Qa("captionschanged",{})};
g.k.create=function(){this.uu()&&this.load()};
g.k.n3=function(){for(var a=this.G.Zd().Ff().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.VP(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&X5(this,b,!0)};
g.k.e5=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ba.push(a);g.eo(this.Ka)};
g.k.onCueRangeExit=function(a){g.sb(this.Ba,a);this.u instanceof A4&&this.u.I&&this.player.Ah([a]);g.eo(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.ea.element.id};
g.k.Z3=function(){l$a(this,this.Oa);this.Oa=null};
g.k.HM=function(){var a=this;if(!this.Nb||!this.C){this.Ka.stop();g.fba(this.Sa);this.Ba.sort(g.qB);var b=this.Ba;if(this.J){var c=g.Bm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())j$a(this,c.value);b={};c=g.t(Object.entries(this.Z));for(var d=c.next();!d.done;b={Yr:b.Yr,ol:b.ol},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Yr=d;b.ol=e;this.Sa[b.Yr]?(b.ol.element.parentNode||(b.ol instanceof E4||b.ol instanceof D4||g.Vc(this.Z,function(f){return function(h,l){l!==f.Yr&&h.u.params.wk===f.ol.u.params.wk&&h.u.params.bj===f.ol.u.params.bj&&h.u.params.jm===f.ol.u.params.jm&&(h.dispose(),delete a.Z[l]);
return l===f.Yr}}(b),this),k$a(this,b.ol.element)),b.ol.yx(this.Sa[b.Yr])):(b.ol.dispose(),delete this.Z[b.Yr])}}};
g.k.e4=function(){b$a(this,{},!0);this.Y.N("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Qa("captionssettingschanged")};
g.k.NZ=function(){var a=a6.le;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:a6.windowColor,windowOpacity:a6.windowOpacity};var b=W8a()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.NU=function(a,b){var c={};Object.assign(c,W8a());Object.assign(c,a);b$a(this,c,b);this.player.Qa("captionssettingschanged")};
g.k.KM=function(){!this.C&&this.loaded&&(g.Qc(this.Z,function(a,b){a.dispose();delete this.Z[b]},this),this.HM())};
g.k.Sg=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ne(b,-2,4);this.NU({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&X5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.D&&(g.AH(this.Y)?Z5(this,!!b):$5(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ma(b))break;if(g.dd(b)){X5(this,null,!0);break}a=g.VP(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==b.languageName||
(c=b.translationLanguage?Q8a(e,b.translationLanguage):e)}n$a(this,b.position);!c||c===this.j&&this.loaded||(b=g.wAa(),a=g.XH(c),b.length&&a===b[b.length-1]||(b.push(a),g.MA("yt-player-caption-language-preferences",b)),P8a(this.Y)&&!this.G.isInline()&&g.MA("yt-player-caption-sticky-language",a),X5(this,c,!0))}else return this.loaded&&this.j&&!P5(this)?g.WH(this.j):{};return"";case "tracklist":return this.u?g.Tg(g.VP(this.u.j,!(!b||!b.includeAsr)),function(f){return g.WH(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||m$a(this,!!b);break;case "sampleSubtitlesCustomized":this.C||m$a(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.D&&a.push("stickyLoading");return a};
g.k.aJ=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.Y.N("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.XH(a));return{cc:b}}return{}};
g.k.Q4=function(){this.loaded&&this.j&&!P5(this)?(g.AH(this.Y)?Z5(this,!1):$5(this,!1),this.unload(),e5(this,!0)&&X5(this,f5(this),!1)):this.rU()};
g.k.rU=function(){this.loaded&&this.j&&!P5(this)||X5(this,P5(this)||!this.j?D5(this,!0):this.j,!0)};
g.k.O0=function(){var a=P5(this);e5(this,a)?X5(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.uu()&&(a?X5(this,D5(this),!1):this.load()))};
g.k.E1=function(){var a=this.G.Zd();a&&!a.isDisposed()&&a.Tv();this.G.isFullscreen()?(this.C=this.Wa=!0,this.loaded&&g$a(this)):(this.Wa="3"===this.Y.controlsType,this.C=a$a(this));X5(this,this.j)};
g.mU.LD(d5,{HM:"smucd"});g.TP("captions",d5);})(_yt_player);
