(function(g){var window=this;'use strict';var Sab=function(a){g.V.call(this,{F:"div",K:"ytp-miniplayer-ui"});this.Cf=!1;this.player=a;this.S(a,"minimized",this.oh);this.S(a,"onStateChange",this.iM)},Uab=function(a){g.UP.call(this,a);
this.u=new g.gF(this);this.j=new Sab(this.player);this.j.hide();g.kP(this.player,this.j.element,4);a.Kf()&&(this.load(),g.ro(a.getRootNode(),"ytp-player-minimized",!0));this.player.N("web_rounded_containers")&&g.ro(a.getRootNode(),"ytp-rounded-miniplayer",!0)};
g.v(Sab,g.V);g.k=Sab.prototype;
g.k.uJ=function(){this.tooltip=new g.TT(this.player,this);g.F(this,this.tooltip);g.kP(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Jc=new g.NQ(this.player);g.F(this,this.Jc);this.Ei=new g.V({F:"div",K:"ytp-miniplayer-scrim"});g.F(this,this.Ei);this.Ei.Ca(this.element);this.S(this.Ei.element,"click",this.wE);var a=new g.V({F:"button",Ga:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.EM()]});g.F(this,a);a.Ca(this.Ei.element);this.S(a.element,"click",this.Kn);
a=new g.z2(this.player,this);g.F(this,a);a.Ca(this.Ei.element);this.Ns=new g.V({F:"div",K:"ytp-miniplayer-controls"});g.F(this,this.Ns);this.Ns.Ca(this.Ei.element);this.S(this.Ns.element,"click",this.wE);var b=new g.V({F:"div",K:"ytp-miniplayer-button-container"});g.F(this,b);b.Ca(this.Ns.element);a=new g.V({F:"div",K:"ytp-miniplayer-play-button-container"});g.F(this,a);a.Ca(this.Ns.element);var c=new g.V({F:"div",K:"ytp-miniplayer-button-container"});g.F(this,c);c.Ca(this.Ns.element);this.gT=new g.pS(this.player,
this,!1);g.F(this,this.gT);this.gT.Ca(b.element);b=new g.nS(this.player,this);g.F(this,b);b.Ca(a.element);this.nextButton=new g.pS(this.player,this,!0);g.F(this,this.nextButton);this.nextButton.Ca(c.element);this.Hi=new g.GT(this.player,this);g.F(this,this.Hi);this.Hi.Ca(this.Ei.element);this.Cc=new g.AS(this.player,this);g.F(this,this.Cc);g.kP(this.player,this.Cc.element,4);this.lE=new g.V({F:"div",K:"ytp-miniplayer-buttons"});g.F(this,this.lE);g.kP(this.player,this.lE.element,4);a=new g.V({F:"button",
Ga:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},W:[g.EM()]});g.F(this,a);a.Ca(this.lE.element);this.S(a.element,"click",this.Kn);a=new g.V({F:"button",Ga:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},W:[g.LM()]});g.F(this,a);a.Ca(this.lE.element);this.S(a.element,"click",this.w2);this.S(this.player,"presentingplayerstatechange",this.Vc);this.S(this.player,"appresize",this.Bb);this.S(this.player,"fullscreentoggled",this.Bb);this.Bb()};
g.k.show=function(){this.Ne=new g.co(this.Kt,null,this);this.Ne.start();this.Cf||(this.uJ(),this.Cf=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Cc.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.Ne&&(this.Ne.dispose(),this.Ne=void 0);g.V.prototype.hide.call(this);this.player.Kf()||(this.Cf&&this.Cc.hide(),this.player.loadModule("annotations_module"))};
g.k.ra=function(){this.Ne&&(this.Ne.dispose(),this.Ne=void 0);g.V.prototype.ra.call(this)};
g.k.Kn=function(){this.player.stopVideo();this.player.Qa("onCloseMiniplayer")};
g.k.w2=function(){this.player.playVideo()};
g.k.wE=function(a){if(a.target===this.Ei.element||a.target===this.Ns.element)g.uL(this.player.Eb())?this.player.pauseVideo():this.player.playVideo()};
g.k.oh=function(){g.ro(this.player.getRootNode(),"ytp-player-minimized",this.player.Kf())};
g.k.qe=function(){this.Cc.kc();this.Hi.kc()};
g.k.Kt=function(){this.qe();this.Ne&&this.Ne.start()};
g.k.Vc=function(a){g.U(a.state,32)&&this.tooltip.hide()};
g.k.Bb=function(){g.TS(this.Cc,0,this.player.fb().getPlayerSize().width,!1);g.DS(this.Cc)};
g.k.iM=function(a){this.player.Kf()&&(0===a?this.hide():this.show())};
g.k.yc=function(){return this.tooltip};
g.k.Jf=function(){return!1};
g.k.Dg=function(){return!1};
g.k.Gj=function(){return!1};
g.k.Fk=function(){return!1};
g.k.Ce=function(){return!1};
g.k.fB=function(){};
g.k.Ko=function(){};
g.k.mw=function(){};
g.k.Il=function(){return null};
g.k.hD=function(){return null};
g.k.Jz=function(){return null};
g.k.Bj=function(){return new g.Dl(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Ut=function(a,b,c,d,e){var f=0,h=d=0,l=g.Rl(a);if(b){c=g.mo(b,"ytp-prev-button")||g.mo(b,"ytp-next-button");var m=g.mo(b,"ytp-play-button"),n=g.mo(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Pl(b,this.element),h=b.x,f=b.y-12):n&&(h=g.mo(b,"ytp-miniplayer-button-top-left"),f=g.Pl(b,this.element),b=g.Rl(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.fb().getPlayerSize().width;e=f+(e||0);l=g.ne(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};
g.k.showControls=function(){};
g.k.Vn=function(){};
g.k.Bk=function(){return!1};
g.k.gB=function(){};
g.k.tx=function(){};
g.k.Gp=function(){};
g.k.nC=function(){};
g.k.qq=function(){};g.v(Uab,g.UP);g.k=Uab.prototype;g.k.onVideoDataChange=function(){if(this.player.N("web_rounded_containers")&&this.player.getVideoData()){var a=16/9;a=this.player.getVideoAspectRatio()>a+.1;g.ro(this.player.getRootNode(),"ytp-rounded-miniplayer-extra-wide-video",a)}};
g.k.create=function(){g.UP.prototype.create.call(this);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.Tj=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.TP("miniplayer",Uab);})(_yt_player);
